name: Full Clone
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  full-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run
        env:
          GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
          SRC_ORG: ${{ secrets.SRC_ORG }}
          DST_ORG: ${{ secrets.DST_ORG }}
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN || 'None' }}
        run: python -u mirror_github_org.py
